name: Auto-Clean

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["OWRT-ALL", "WRT-TEST", "OWRT-ONE"]
    types: [completed]
  schedule:
    - cron: '30 17 2/6 * *'  # 每6天的凌晨1点30执行

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all

jobs:
  auto_clean:
    if: >-
      github.event_name == 'workflow_dispatch' || 
      github.event_name == 'schedule' || 
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 0
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
