name: OWRT-ONE

on:
  workflow_dispatch:
    inputs:
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    secrets:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}
      WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
    with:
      #编译平台
      WRT_TARGET: Mediatek-hanwckf
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ImmortalWrt
      #默认WIFI名
      WRT_WIFI: ImmortalWrt
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/hanwckf/immortalwrt-mt798x.git
      # 源码分支
      WRT_BRANCH: openwrt-21.02
      # 源码名称
      WRT_SOURCE: immortalwrt-mt798x.git
      # 源码用户名
      WRT_UNAME: hanwckf
      # 仅输出配置文件
      WRT_TEST: ${{ inputs.TEST }}
      
