name: WRT-TEST

on:
  # 手动编译
  workflow_dispatch:
    inputs:
      TARGET:
        default: 'Mediatek'
        required: true
        type: choice
        options: [Mediatek, Mediatek-hanwckf, Mediatek-Padavanonly]
      SOURCE:
        default: 'immortalwrt.git'
        required: true
        type: choice
        options: [immortalwrt.git, immortalwrt-mt798x.git, immortalwrt-mt798x-23.05.git]
      UNAME:
        default: 'immortalwrt'
        required: true
        type: choice
        options: [immortalwrt, hanwckf, padavanonly]
      BRANCH:
        default: 'master'
        required: true
        type: choice
        options: [master, openwrt-21.02, openwrt-23.05]
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{inputs.SOURCE}}
    # 调用公用编译核心 WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    secrets:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}
      WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
    with:
      # 编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      # 默认主题
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: ImmortalWrt
      # 默认 WIFI 名
      WRT_WIFI: ImmortalWrt
      # 默认地址
      WRT_IP: 192.168.10.1
      # 默认密码，仅作提示，修改无用
      WRT_PW: 无
      # 源码链接
      WRT_REPO: https://github.com/${{ inputs.UNAME }}/${{ inputs.SOURCE }}
      # 源码分支
      WRT_BRANCH: ${{ inputs.BRANCH }}
      # 源码名称
      WRT_SOURCE: ${{ inputs.SOURCE }}
      # 源码用户名
      WRT_UNAME: ${{ inputs.UNAME }}
      # 仅输出配置文件
      WRT_TEST: ${{ inputs.TEST }}
      
